### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_FuelFrenzy.Tembelan#2]
- [x] check killed all tanktrucks / players
- [x] display stats
- [x] test dedicated
- [x] test wave respawn
- [x] add ammunition to base
